image: zapier/python-docker:latest

.cache-pull: &cache-pull
  cache:
    key: "${CI_RUNNER_ID}"
    policy: pull
    paths:
      - .venv

stages:
  - install
  - test
  - build
  - deploy

before_script:
  - poetry config settings.virtualenvs.in-project true
  - poetry config settings.virtualenvs.path .venv
  - poetry install

install:
  stage: install
  cache:
    key: "${CI_RUNNER_ID}"
    paths:
      - .venv
  script:
    - poetry install

test:
  stage: test
  <<: *cache-pull
  script:
    - poetry run flake8 sneak
    - poetry run python -m unittest discover

build:
  stage: build
  <<: *cache-pull
  script:
    - poetry build
  artifacts:
    untracked: true
    paths:
    - dist
    expire_in: 1 week

deploy-prod:
  stage: deploy
  <<: *cache-pull
  script:
    - poetry config repositories.zapier https://pypi.zapier.com/
    - poetry publish -r zapier -u $prod_pypi_user -p $prod_pypi_pass
  when: manual
